const CATEGORIES={expense:['Moradia','Alimentação','Transporte','Saúde','Educação','Lazer','Cartões de Crédito','Impostos','Assinaturas','Outros'],income:['Salário','Pró-labore','Freelance','Investimentos','Reembolso','Outras receitas']};
const KEY='gfp.v1';
const $=id=>document.getElementById(id);
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const percent=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1});
const monthName=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'});
let state=load();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{transactions:[],budget:0,theme:'light'}}catch{return{transactions:[],budget:0,theme:'light'}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dateBR(v){return new Date(v+'T12:00:00').toLocaleDateString('pt-BR')}
function selectedMonth(){return $('monthFilter').value}
function filtered(){const m=selectedMonth(),t=$('typeFilter').value,c=$('categoryFilter').value,q=$('searchFilter').value.trim().toLowerCase();return state.transactions.filter(x=>(!m||x.date.startsWith(m))&&(t==='all'||x.type===t)&&(c==='all'||x.category===c)&&(!q||x.description.toLowerCase().includes(q)||x.notes.toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt)}
function totals(items){return items.reduce((a,x)=>(a[x.type]+=x.amount,a),{income:0,expense:0})}
function render(){const items=filtered(),sum=totals(items),balance=sum.income-sum.expense,rate=sum.income?balance/sum.income*100:0;$('incomeValue').textContent=money.format(sum.income);$('expenseValue').textContent=money.format(sum.expense);$('balanceValue').textContent=money.format(balance);$('balanceValue').className=balance<0?'danger':'';$('incomeCount').textContent=count(items,'income');$('expenseCount').textContent=count(items,'expense');$('savingsRate').textContent=`Poupança: ${percent.format(rate)}%`;$('budgetValue').textContent=money.format(state.budget);$('budgetProgress').textContent=state.budget?`${percent.format(Math.min(sum.expense/state.budget*100,999))}% utilizado`:'Defina sua meta';$('transactionCount').textContent=`${items.length} ${items.length===1?'registro':'registros'}`;$('transactionsBody').innerHTML=items.map(row).join('');$('emptyState').style.display=items.length?'none':'block';renderCategories(items);renderTrend();updateCategoryFilter();}
function count(items,type){const n=items.filter(x=>x.type===type).length;return `${n} ${n===1?'lançamento':'lançamentos'}`}
function row(x){return `<tr><td>${dateBR(x.date)}</td><td><strong>${esc(x.description)}</strong>${x.notes?`<br><small>${esc(x.notes)}</small>`:''}</td><td>${esc(x.category)}</td><td><span class="pill ${x.type}">${x.type==='income'?'Receita':'Despesa'}</span></td><td class="right amount ${x.type}">${x.type==='income'?'+':'−'} ${money.format(x.amount)}</td><td><div class="row-actions"><button data-edit="${x.id}" aria-label="Editar">✎</button><button data-delete="${x.id}" aria-label="Excluir">×</button></div></td></tr>`}
function renderCategories(items){const map={};items.filter(x=>x.type==='expense').forEach(x=>map[x.category]=(map[x.category]||0)+x.amount);const list=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,7),max=list[0]?.[1]||1;$('categoryChart').className='bars'+(list.length?'':' empty');$('categoryChart').innerHTML=list.length?list.map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><span class="bar-value">${money.format(v)}</span></div>`).join(''):'Nenhuma despesa no período.'}
function renderTrend(){const now=new Date(),months=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),key=d.toISOString().slice(0,7);months.push({key,label:d.toLocaleDateString('pt-BR',{month:'short'}),...totals(state.transactions.filter(x=>x.date.startsWith(key)))})}const max=Math.max(1,...months.flatMap(x=>[x.income,x.expense]));$('trendChart').innerHTML=months.map(x=>`<div class="trend-group" title="${x.label}: receitas ${money.format(x.income)}, despesas ${money.format(x.expense)}"><div class="trend-bar income" style="height:${x.income/max*180}px"></div><div class="trend-bar expense" style="height:${x.expense/max*180}px"></div><span class="trend-label">${x.label}</span></div>`).join('')}
function updateCategoryFilter(){const current=$('categoryFilter').value,all=[...new Set(state.transactions.map(x=>x.category))].sort();$('categoryFilter').innerHTML='<option value="all">Todas</option>'+all.map(x=>`<option>${esc(x)}</option>`).join('');$('categoryFilter').value=all.includes(current)?current:'all'}
function updateFormCategories(type,value=''){const list=CATEGORIES[type];$('categoryInput').innerHTML=list.map(x=>`<option>${x}</option>`).join('');if(list.includes(value))$('categoryInput').value=value}
function openForm(item){$('transactionForm').reset();$('transactionId').value=item?.id||'';$('dialogTitle').textContent=item?'Editar lançamento':'Novo lançamento';const type=item?.type||'expense';document.querySelector(`input[name=transactionType][value=${type}]`).checked=true;updateFormCategories(type,item?.category);$('descriptionInput').value=item?.description||'';$('amountInput').value=item?.amount||'';$('dateInput').value=item?.date||new Date().toISOString().slice(0,10);$('notesInput').value=item?.notes||'';$('transactionDialog').showModal()}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function exportCsv(){const rows=[['data','descricao','categoria','tipo','valor','observacao'],...state.transactions.map(x=>[x.date,x.description,x.category,x.type,x.amount.toFixed(2),x.notes])];download('GFP_Lancamentos.csv',rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),'text/csv')}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);return lines.slice(1).map(line=>{const v=[];let s='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){s+='"';i++}else if(c==='"')q=!q;else if(c===';'&&!q){v.push(s);s=''}else s+=c}v.push(s);return{id:uid(),date:v[0],description:v[1],category:v[2],type:v[3]==='income'?'income':'expense',amount:Number(String(v[4]).replace(',','.')),notes:v[5]||'',createdAt:Date.now()}}).filter(x=>x.date&&x.description&&x.amount>0)}
$('newButton').onclick=()=>openForm();$('closeDialog').onclick=$('cancelDialog').onclick=()=>$('transactionDialog').close();
document.querySelectorAll('input[name=transactionType]').forEach(x=>x.onchange=()=>updateFormCategories(x.value));
$('transactionForm').onsubmit=e=>{e.preventDefault();const id=$('transactionId').value,item={id:id||uid(),type:document.querySelector('input[name=transactionType]:checked').value,description:$('descriptionInput').value.trim(),amount:Number($('amountInput').value),date:$('dateInput').value,category:$('categoryInput').value,notes:$('notesInput').value.trim(),createdAt:id?(state.transactions.find(x=>x.id===id)?.createdAt||Date.now()):Date.now()};if(!item.description||!item.date||!(item.amount>0))return;state.transactions=id?state.transactions.map(x=>x.id===id?item:x):[...state.transactions,item];save();$('transactionDialog').close();render();toast(id?'Lançamento atualizado.':'Lançamento cadastrado.')};
$('transactionsBody').onclick=e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)openForm(state.transactions.find(x=>x.id===edit.dataset.edit));if(del&&confirm('Excluir este lançamento?')){state.transactions=state.transactions.filter(x=>x.id!==del.dataset.delete);save();render();toast('Lançamento excluído.')}};
['monthFilter','typeFilter','categoryFilter','searchFilter'].forEach(id=>$(id).addEventListener(id==='searchFilter'?'input':'change',render));
$('saveBudgetButton').onclick=()=>{state.budget=Math.max(0,Number($('budgetInput').value)||0);save();render();toast('Orçamento atualizado.')};
$('exportButton').onclick=exportCsv;$('backupButton').onclick=()=>download(`GFP_Backup_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state,null,2),'application/json');$('importButton').onclick=()=>$('fileInput').click();
$('fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const text=await f.text();if(f.name.endsWith('.json')){const data=JSON.parse(text);if(!Array.isArray(data.transactions))throw Error();state={transactions:data.transactions,budget:Number(data.budget)||0,theme:data.theme||'light'}}else state.transactions=[...state.transactions,...parseCsv(text)];save();init();toast('Dados importados com sucesso.')}catch{toast('Arquivo inválido. Nenhum dado foi alterado.')}e.target.value=''};
$('themeButton').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();document.body.classList.toggle('dark',state.theme==='dark')};
function init(){document.body.classList.toggle('dark',state.theme==='dark');const today=new Date();$('monthFilter').value=today.toISOString().slice(0,7);$('periodLabel').textContent=monthName.format(today);$('budgetInput').value=state.budget||'';updateFormCategories('expense');render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}init();
